### ISSUE TITLE
Is there a way to keep the search bar visible when the Eloquent is made narrow?

### ISSUE THREAD

**Issue by Thomas-Cee** [mdbergmann/Eloquent#47]
Can the search bar remain visible when the Eloquent window is made narrow? It shows up when the window is stretched, but disappears when made narrow. I remember this was not an issue with my old Macbook running OSX 10.7.5, maybe leading me to think it has to do with my newer MB running OSX 10.13.3? 

THANK YOU FOR YOUR WORK ON THIS PROJECT!!! Loooooooove it.

I hope the pictures uploaded correctly. 

I am new to GitHub, am I doing this right?
I am a little foggy on how this all works, but I have used Eloquent since way back when when it was MacSword on my 2007 Macbook. It's for me, the perfect Bible program.

![screenshot](https://user-images.githubusercontent.com/38837288/39645187-4c502942-4f8c-11e8-8da3-ca4a2b8a23bc.png)
![screenshot](https://user-images.githubusercontent.com/38837288/39645191-508ac738-4f8c-11e8-9347-480cf6748789.png)
![screenshot](https://user-images.githubusercontent.com/38837288/39645196-5388ae6e-4f8c-11e8-83e5-63da881c59d6.png)

**Comment by tdselgas** [comment]
I am having the same issue.

**Comment by mdbergmann** [comment]
The search text field has a fixed size. When the window width gets below this fixed size it macOS will hide it completely.
I'm looking into that.

**Comment by mdbergmann** [comment]
Fixed.

**Comment by Thomas-Cee** [comment]
So awesome. Thanks for your work on this awesome project.

**Comment by Thomas-Cee** [comment]
Ohhhh dear... I am updated to 2.6.3, and I am still having the same issue sadly... I have closed Eloquent, reopened, restarted the computer to make sure there was nothing residual in the system, and am still seeing the same issue!

**Comment by mdbergmann** [comment]
Well, how narrow do you need it?
Do you close the left sidebar?

Attached picture shows the most narrow window. The window cannot be made smaller/more narrow.
But the search bar is still there.
<img width="400" alt="bildschirmfoto 2018-06-21 um 08 38 14" src="https://user-images.githubusercontent.com/2143978/41701938-9e3ec796-752e-11e8-817c-d016cc095965.png">

**Comment by Thomas-Cee** [comment]
Maybe it's me... I did a 1 minute screen record to show it. It's most narrow setting is perfect, but somehow my copy is behaving differently... I am not sure why...
https://youtu.be/C2JHwZY5d_Q

**Comment by mdbergmann** [comment]
OK, thanks for the screencast (what software did you use there?)
It could be that you have to reset the toolbar to new defaults, or at least replace the search text field.

Try right-click on the toolbar, then 'Customize toolbar'.
In this panel you remove (drag&drop into the panel) the old search field, and set the default search field back to the toolbar.
